version: '3.7'

services:
  jibber_jabber_client:
    container_name: jibber-jabber-client
    image: ghcr.io/facundobocalandro/jj-client-dev:latest
    ports:
      - 1337:80

  jibber_jabber_proxy:
    container_name: jibber-jabber-proxy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80

  jibber_jabber_posts:
    container_name: jibber-jabber-posts
    image: ghcr.io/facundobocalandro/jj-posts-dev:latest
    ports:
      - 8082:8080
    env_file:
      - posts.env
  jibber_jabber_posts_db:
    container_name: jibber_jabber_posts_db
    image: postgres:12
    ports:
      - 5432:5432
    env_file:
      - posts-database.env
    volumes:
      - jjposts:/var/lib/postgresql/data
  jibber_jabber_auth:
    container_name: jibber-jabber-auth
    image: ghcr.io/facundobocalandro/jj-auth-dev:latest
    ports:
      - 8081:8080
    env_file:
      - auth.env
  jibber_jabber_auth_db:
    container_name: jibber_jabber_auth_db
    image: postgres:12
    ports:
      - 5433:5432
    env_file:
      - auth-database.env
    volumes:
      - jjauth:/var/lib/postgresql/data

volumes:
  jjposts:
  jjauth: