version: '3.7'

services:
  jibber-jabber-client:
    image: ghcr.io/facundobocalandro/jj-client-dev:latest
    ports:
      - 80:80

  jibber-jabber-proxy:
    image: ghcr.io/facundobocalandro/jj-proxy-dev:latest
    ports:
      - 8080:8080

  jibber-jabber-posts:
    image: ghcr.io/facundobocalandro/jj-posts-dev:latest
    ports:
      - 8082:8080
    env_file:
      - posts.env
  jibber_jabber_posts_db:
    image: postgres:12
    ports:
      - 5432:5432
    env_file:
      - posts-database.env
    volumes:
      - jjposts:/var/lib/postgresql/data
  jibber_jabber_auth:
    image: ghcr.io/facundobocalandro/jj-posts-dev:latest
    ports:
      - 8081:8080
    env_file:
      - auth.env
  jibber_jabber_auth_db:
    image: postgres:12
    ports:
      - 5433:5432
    env_file:
      - auth-database.env
    volumes:
      - jjauth:/var/lib/postgresql/data

volumes:
  jjposts:
  jjauth: